### ISSUE TITLE
userId = null on external request

### ISSUE THREAD

**Issue by mfranzs** [mhagmajer/server-router#2]
I'm trying to use this package to set up an externally accessible API where a consumer accesses mysite.com/api_endpoint and the server returns a response. I want the server's response to depend on the current logged in user's ID (the API call is coming from a browser in which the user is logged into mysite.com).

However, when accessed in the route method, _this.userId_ is null. Looking through the code, I think it might be because of this line:

https://github.com/mhagmajer/server-router/blob/0eb7746c86f83c0d061714264b85da279a878a98/src/server/server-router.js#L342

Why is this setup this way? Can you not get userId's in this manner? I thought that this functionality is what separated this package from something like Picker.

Code for reference:
```
const serverRouter = new ServerRouter();
WebApp.connectHandlers.use(serverRouter.middleware);

serverRouter.addPath({
  path: '/api_endpoint',
  args: (() => {}),
  async route() {
    this.res.end(this.userId+ "test");
  },
});
```

**Comment by mhagmajer** [comment]
@mfranzs, first of all thanks for posting your question. For authentication to work there must be an authentication token present in the params of the url, eg.:

```
mysite.com/api_endpoint?_userId=oPwEZMPDWmdoSCQSi&_token=m72JpzQeQSeNs9cTx
```

This token needs to be obtained on the client-side before users are redirected to the server-side. This is because Meteor doesn't use cookies but stores the authentication data in localStorage. Adding this params is done automatically for you, provided that you use `ServerRouterClient` on the client-side and throw `AuthenticationRequiredError` from your path handler.

You can read more about this and see specific examples in the introductory [blog post](https://blog.hagmajer.com/server-side-routing-with-authentication-in-meteor-6625ed832a94) I wrote about this package.

Please do let me know if you have more questions.

**Comment by mhagmajer** [comment]
@mfranzs, feel free to reopen if you have more questions.
